version: "3.6"
services:
  backend:
    build:
      context: ./myplanner/server/
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./myplanner/client
    ports:
      - "3000:3000"
    depends_on:
      - backend
