version: "3.6"
services:
  frontend:
    build:
      context: ./myplanner/client
    ports:
      - "80:80"
  # backend:
  #   build:
  #     context: ./myplanner/server/
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./myplanner/server:/code
  #   depends_on:
  #     - db
  # db:
  #   image: postgres:10.5
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5438:5432"
