import os

from flask import Flask
from flask_restful import Api
from flask_jwt_extended import JWTManager
from flasgger import Swagger
from flask_cors import CORS

from db import db
from resources.userResource import UserRegister, UserAll, UserLogin, UserDelete
from resources.itemResource import ItemAdd, ItemAll, Item, ItemAllSpecificUser
from resources.eventResource import (
    EventAdd,
    EventEdit,
    EventGetUnassigned,
    EventGetAssigned,
    EventGetUpcoming,
)
from load_sample import load


def init_app():

    app = Flask(__name__)
    app.secret_key = "abcd"  # To-do: Should change this to an autogenerated string
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL", "sqlite://")

    Swagger(app)
    JWTManager(app)
    CORS(app)

    return app


def add_routes(app):

    api = Api(app)
    api.add_resource(UserRegister, "/user/register")
    api.add_resource(UserAll, "/user/all")
    api.add_resource(UserLogin, "/user/login")
    api.add_resource(UserDelete, "/user/delete/<int:id>")

    api.add_resource(ItemAllSpecificUser, "/item/all")
    api.add_resource(ItemAll, "/item/all/admin")
    api.add_resource(ItemAdd, "/item/add")
    api.add_resource(Item, "/item/<int:item_id>")

    api.add_resource(EventAdd, "/event")
    api.add_resource(EventEdit, "/event/<int:event_id>")
    api.add_resource(EventGetUnassigned, "/event/all/unassigned")
    api.add_resource(EventGetAssigned, "/event/all/assigned")
    api.add_resource(EventGetUpcoming, "/event/upcoming/<int:no_weeks_to_look_ahead>")

    return app


app = init_app()
app = add_routes(app)
db.init_app(app)


@app.before_first_request
def create_tables():
    db.drop_all()
    db.create_all()
    db.session.commit()
    load()
